version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-https-proxy
    ports:
      - "4443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-backend
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=https://localhost:4443/api
      - HTTPS=false
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend: